### ISSUE TITLE
Inference on custom dataset

### ISSUE THREAD

**Issue by allansp84** [facebookresearch/PoseWarper#16]
Dear All,

Congrats for the work and Thank you for making this code available for the community.
Could you provide me some guidance on how could I make inferences on a custom dataset, please? 

Best,

**Comment by gberta** [comment]
The easiest way is as follows. You would need to create a COCO style JSON file that stores detected bounding boxes for each person in each of your images (see the provided val_boxes.json or test_boxes.json files for a reference). You would also need to create a COCO style JSON file that store all information related to your images similar to the posetrack JSON files that are provided with this repo (see posetrack_test.json). Afterwards, you could just run the same "python tools/test.py" command which is invoked in posetrack17_helper.py/posetrack18_helper.py. Before you do so, though, you would need to change several config options, specifically cfg.DATASET.JSON_FILE should point to your new JSON file that stores information about your images, and cfg.TEST.COCO_BBOX_FILE should point to your new JSON file that stores detected bounding boxes associated with each person in your images. You should also run your code with cfg.MODEL.EVALUATE False option so that the PoseTrack evaluation is disabled. Lastly, if you include SAVE_PREDS True option, the detected keypoints will be saved in a '.h5' file. Hope this helps!

**Comment by allansp84** [comment]
Hi gberta,

Thank you for your prompt response.  I did what you said, and it seems that another variable needs to be set, as we can see in the execution log below. In the file "/home/allansp/PoseWarper/tools/../lib/dataset/posetrack_PoseAgg.py", line 663, there is a variable named cfg.POSETRACK_ANNOT_DIR that should receive the path to a set of JSON files. So, what kind of JSON files should I have on this directory?  Could you help me go through this issue, please?

### Execution Log
\########################################
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
=> classes: ['__background__', 'person']
=> num_images: 129
=> load 0 samples
Saving preds...
PoseWarper_supp_files/data/PoseWarper/V250_N115/out/keypoint_preds/delta0_keypoints.h5
\###  Method: Temporal Pose Aggregation via PoseWarper ###
Traceback (most recent call last):
  File "tools/test.py", line 169, in <module>
    main()
  File "tools/test.py", line 165, in main
    final_output_dir, tb_log_dir)
  File "/home/allansp/PoseWarper/tools/../lib/core/function_PoseAgg.py", line 282, in validate
    name_values, perf_indicator = val_dataset.evaluate(config, all_preds, output_dir, all_boxes, filenames_map, filenames, imgnums)
  File "/home/allansp/PoseWarper/tools/../lib/dataset/posetrack_PoseAgg.py", line 667, in evaluate
    out_filenames, L = video2filenames(annot_dir)
  File "/home/allansp/PoseWarper/tools/../lib/dataset/posetrack_PoseAgg.py", line 189, in video2filenames
    mat_files = [f for f in os.listdir(pathtodir) if
FileNotFoundError: [Errno 2] No such file or directory: ''

### Command line:
python tools/test.py \
    --cfg experiments/posetrack/hrnet/w48_384x288_adam_lr1e-4_PoseWarper_inference_temporal_pose_aggregation.yaml \
    OUTPUT_DIR PoseWarper_supp_files/data/PoseWarper/V250_N115/out/ \
    LOG_DIR PoseWarper_supp_files/data/PoseWarper/V250_N115/log/ \
    DATASET.IMG_DIR data/images_renamed/ \
    DATASET.JSON_FILE data/jsons/posetrack_mydata.json \
    TEST.MODEL_FILE PoseWarper_supp_files//pretrained_models/PoseWarper_posetrack17.pth \
    TEST.COCO_BBOX_FILE data/val_boxes.json \
    MODEL.EVALUATE False \
    SAVE_PREDS True \
    EXPERIMENT_NAME "Temporal Pose Aggregation via PoseWarper"

Best,

**Comment by gberta** [comment]
cfg.POSETRACK_ANNOT_DIR is a location for ground truth json files, which shouldn't be necessary in your case. Even though the program crashes at L282 of function_PoseAgg.py, your prediction files should be successfully saved in an .h5 file. Please check for that. 

To prevent the crash, you would want to add a condition that if config.MODEL.EVALUATE is False, none of the code from L281-L319 should be executed (you can achieve that by adding a "return None" statement before L281. Hope this helps.

**Comment by allansp84** [comment]
Thank you, gberta.
