### ISSUE TITLE
I'm curious how do you determine which detected bounding box belongs to which person?

### ISSUE THREAD

**Issue by ArchNew** [facebookresearch/PoseWarper#22]
I understand this work only involves pose estimation on video, doesn't include tracking. According to your paper, some of your experiments involve a human detector, such as the experiment Table 2 in the paper shows. Normally, such an experiment doesn't need tracking, but your experiment has a "temporal pose aggregation" process, needs to aggregate pose information cross frames. In order to do that, you need to track the person across frames. With detected bounding box, how do you do that? Or your results in Table 2 are evaluated on the ground truth bounding box?

I temporarily closed the issue because I saw the figure 1 in the paper. But upon further consideration, your PoseWarper is trained on individuals cropped from the image according to their ground truth bounding boxes. So, I find my question is still valid.

**Comment by ArchNew** [comment]
I think I got the answer.

**Comment by gberta** [comment]
The cropped boxes have enough context around them for temporal pose aggregation to be valid. Given a box for frame t, we use the same box for frame t+\delta. The assumption is that the motion between the two frames will be relatively small, and therefore the same box in frame t+\delta will contain enough relevant information so that our model would be able to leverage  it for improved pose detection.

**Comment by ArchNew** [comment]
Thanks!
