### ISSUE TITLE
I have some questions about training pipleline and model initialization on the experiment "Video Pose Propagation"

### ISSUE THREAD

**Issue by ArchNew** [facebookresearch/PoseWarper#24]
### About the pipeline
If I understand correctly. You first initialize your base HRNet model with the official HRNet model trained on COCO keypoints, then train your base HRNet model on posetrack dataset for 10 epochs at lr1e-4 (step down at 5,7). After that, you train the PoseWarper for another 20 epochs also at lr1e-4 (step down at 10, 15) with the HRNet part fixed.
Do I understand it correctly?

### Abount model initialization
There are 15 keypoints in PoseTrack and 17 keypoints in COCO keypoints. And there also differences in those existing keypoints. PoseTrack doesn't have eyes and ears, and COCO keypoints doesn't have head_top and head_bottom.
You directly initialize the model for posetrack using the model trained on COCO keypoints, and expand posetrack ground truth with two extra keypoints labeled with 0. Then you train your model according to the PoseTrack ground truth. 
Is it OK to train the channels for two eyes in the last layer of the model for head_top and head_bottom? Re-initialize those two channels with nn.normal_() shouldn't be better?

**Comment by gberta** [comment]
Your description of the pipeline sounds correct to me. However, I'm not sure about exact LR and epoch numbers, since it's been a while since I worked on this, so you should check the configuration files to make sure. 

In regards to PoseTrack and COOC keypoint matching, you should check the code for conversion between COCO and PoseTrack heatmaps. I believe that the conversion code is located somewhere either in the utils or datasets section.

**Comment by ArchNew** [comment]
Thanks!
