### ISSUE TITLE
inference in the wild

### ISSUE THREAD

**Issue by richlaji** [facebookresearch/PoseWarper#5]
I can run posetrack18_helper.py now. What should I do if I want to inference in the wild~Thank you！

**Comment by gberta** [comment]
The easiest way is as follows. You would need to create a COCO style JSON file that stores detected bounding boxes for each person in each of your images (see the provided val_boxes.json or test_boxes.json files for a reference). You would also need to create a COCO style JSON file that store all information related to your images similar to the posetrack JSON files that are provided with this repo (see posetrack_test.json). Afterwards, you could just run the same "python tools/test.py" command which is invoked in posetrack17_helper.py/posetrack18_helper.py. Before you do so, though, you would need to change several config options, specifically cfg.DATASET.JSON_FILE should point to your new JSON file that stores information about your images, and cfg.TEST.COCO_BBOX_FILE should point to your new JSON file that stores detected bounding boxes associated with each person in your images. You should also run your code with cfg.MODEL.EVALUATE False option so that the PoseTrack evaluation is disabled. Lastly, if you include SAVE_PREDS True option, the detected keypoints will be saved in a '.h5' file. Hope this helps!

**Comment by richlaji** [comment]
> The easiest way is as follows. You would need to create a COCO style JSON file that stores detected bounding boxes for each person in each of your images (see the provided val_boxes.json or test_boxes.json files for a reference). You would also need to create a COCO style JSON file that store all information related to your images similar to the posetrack JSON files that are provided with this repo (see posetrack_test.json). Afterwards, you could just run the same "python tools/test.py" command which is invoked in posetrack17_helper.py/posetrack18_helper.py. Before you do so, though, you would need to change several config options, specifically cfg.DATASET.JSON_FILE should point to your new JSON file that stores information about your images, and cfg.TEST.COCO_BBOX_FILE should point to your new JSON file that stores detected bounding boxes associated with each person in your images. You should also run your code with cfg.MODEL.EVALUATE False option so that the PoseTrack evaluation is disabled. Lastly, if you include SAVE_PREDS True option, the detected keypoints will be saved in a '.h5' file. Hope this helps!

Thank you very much! I'll try it right away.

**Comment by richlaji** [comment]
It works！Thank you again！
